// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAmz7BMOsZdZPFAIa2kDy1ABrrH2iinp4',
    appId: '1:734573672944:web:3eeba93bcb09efc1428535',
    messagingSenderId: '734573672944',
    projectId: 'btma-8b710',
    authDomain: 'btma-8b710.firebaseapp.com',
    storageBucket: 'btma-8b710.firebasestorage.app',
    measurementId: 'G-G4HJHTXMD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCpz5aGyagQyLUlwT0VezpLhsnZvUndSw',
    appId: '1:734573672944:android:288c9e07fbc6b369428535',
    messagingSenderId: '734573672944',
    projectId: 'btma-8b710',
    storageBucket: 'btma-8b710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD64z35NYRMEPRcPff6J90Q6Sz59d7Cc-U',
    appId: '1:734573672944:ios:0e9a88aadebc085f428535',
    messagingSenderId: '734573672944',
    projectId: 'btma-8b710',
    storageBucket: 'btma-8b710.firebasestorage.app',
    iosBundleId: 'com.rd.breakthrough',
  );
}
